name: Test expose web server with LocalTunnel

on: 
  workflow_dispatch:

jobs:
  expose-webserver:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.7
      with:
        clean: true  # Ensure the workspace is cleaned before checkout

    - name: Set up Go environment
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'
        cache: false

    - name: Clean up the output directory
      run: |
        rm -rf output

    - name: Install LocalTunnel
      run: |
        npm install -g localtunnel

    - name: Build the HTMX web service
      run: |
        go build -o webserver .
      

    - name: Start LocalTunnel and wait for HTMX web service
      run: |
        TIMESTAMP=$(date +%s)
        SUBDOMAIN="manual-test-${TIMESTAMP}"
        IP_ADDRESS=$(curl -s ipv4.icanhazip.com | tr -d '\n')
        lt --port 8080 --subdomain ${SUBDOMAIN} > url.txt &
        sleep 5  # Wait for LocalTunnel to start up
        echo "Your service is available at: https://${SUBDOMAIN}.loca.lt"
        echo "PLEASE NOTE: The IP address is required as the password on the webpage: ${IP_ADDRESS}"
        echo "If you get a 'Bad Gateway' error, refresh the page."
        ./webserver  # Run the HTMX web server in the foreground (blocking)

    - name: List all generated test result .json files
      run: find output -name '*-result.json'

    - name: Print the content of all .json files in the output directory
      run: find output -name '*-result.json' -exec cat {} \;

    - name: Upload test results
      uses: actions/upload-artifact@v4.4.0
      with:
        name: manual-test-results
        path: output/
