name: Test expose web server with localhost.run

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Select a tag'
        required: true
        default: 'PV'
        type: choice
        options:
          - PV
          - IV
          - pPV
          - pIV

jobs:
  collect-manual-test-result:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.7
      with:
        clean: true  # Ensure the workspace is cleaned before checkout

    - name: Set up Go environment
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'
        cache: false

    - name: Clean up the output directory
      run: |
        rm -rf output

    - name: Build the HTMX web service
      run: |
        go build -o webserver .

    - name: Expose service via localhost.run
      run: |
        ssh -o StrictHostKeyChecking=no -R 80:localhost:8080 nokey@localhost.run > localhostrun.txt 2>&1 &
        sleep 5  # Wait for SSH tunnel to establish
  
    - name: Show localhost.run URL
      run: |
        cat localhostrun.txt
        echo "Your web service is now accessible at the URL above."

    - name: Start the HTMX web service and wait for it to exit
      run: |
        TAG_LOWER=$(echo "${{ github.event.inputs.tag }}" | tr '[:upper:]' '[:lower:]')
        ./webserver --${TAG_LOWER}  # Run the HTMX web server with the selected tag

    - name: List all generated test result .json files
      run: find output -name '*-result.json'

    - name: Print the content of all .json files in the output directory
      run: find output -name '*-result.json' -exec cat {} \;

    - name: Upload test results
      uses: actions/upload-artifact@v4.4.0
      with:
        name: manual-test-results
        path: output/
